# Build and autotest script for PX4 Firmware
# http://travis-ci.org

sudo: required

services:
  - docker

language: cpp

git:
  submodules: true

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "bTa5MzuaQQJ5Tl1TEh81nX20RSjMT2nhn1rbFOyH2bYu3UxVkrIbQjWNxlvxqU0gFQ6KeuB7kcGkjUXsNxrrtC/M3jlkF7Madw4dlXN7rBbUxZ8XUeU5s5CK/3ZWaG5kQG3DMWGwRbR54GaJ9dSkCeFNnJoKwoIAtuzdprBpbig="

matrix:
  fast_finish: true
  include:
    - env: BUILD_TARGET=coverity_scan
      dist: trusty
      if: branch = coverity_scan

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
  - sudo pip install empy jinja2 numpy toml

script:
  - make posix_sitl_default

addons:
  coverity_scan:
    project:
      name: "PX4/Firmware"
      description: "Build submitted via Travis CI"
    notification_email: ci@px4.io
    build_command_prepend: "make distclean"
    build_command: "make posix_sitl_default"
    branch_pattern: coverity_scan
